name: Docker Image languajeJs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4   

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}  
      
    - name: Build the Docker image
      run: docker build -t kevinseya/languaje-js-app .

    - name: Publish image to docker hub
      run: docker push kevinseya/languaje-js-app:latest  
